# CI de Nível 01 - Disparo Manual através de clique

# nome da pipeline
name: 'Execução Manual e PR Review'


# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch

on:
    workflow_dispatch:

    pull_request:
        types:
        - opened
        - synchronize
        - reopened

# tarefas dentro da pipeline = jobs
jobs: 
    pr-agent:
    if: github.event_name == 'pull_request' && github.event.action == 'opened'

    runs-on: ubuntu-latest

    permissions: 
        contents: read 
        pull-requests: write 
        issues: write

    steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Gerar descrição do PR
          uses: Codium-ai/pr-agent@main
          env:
            OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            command: describe

        - name: Revisar PR
          uses: Codium-ai/pr-agent@main
          env:
            OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            command: review

        - name: Sugerir melhorias
          uses: Codium-ai/pr-agent@main
          env:
            OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            command: improve



    # nome do job
=======
#tarefas dentro da pipeline = jobs

jobs:
    #nome do job
    e2e-tests:
        if: github.event_name == 'workflow_dispatch'
        # maquina onde o job vai rodar
        runs-on: ubuntu-latest

        # passos do job
        steps:
            # clone do projeto
            - uses: actions/checkout@v4

            # instalção do node
            - uses: actions/setup-node@v4
              with:
                  node-version: 24.x

            # instalação do Yarn
            - name: Instalando Yarn
              run: npm install -g yarn
            
            #   instalação das dependências
            - name: Instalando dependências
              run: yarn
            
            # instalação dos Browsers do Playwright
            - name: Instalando Browsers do Playwright
              run: yarn playwright install
            
            # executar os testes e2e
            - name: Executando testes e2e
              run: yarn run e2e